apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ml-serving
  labels:
    app: {{ .Release.Name }}-ml-serving
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-ml-serving
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
